spring.application.name=Military_Asset_Management_System


spring.datasource.url=jdbc:mysql://localhost:3306/mil_assets?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=Annappa@8105

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=9094
